name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install vite @vitejs/plugin-react
        npm install react react-dom
        npm install @types/react @types/react-dom
        npm install typescript
        npm install tailwindcss @tailwindcss/typography
        npm install lucide-react
        npm install motion
        npm install class-variance-authority clsx tailwind-merge
        npm install @radix-ui/react-accordion
        npm install @radix-ui/react-alert-dialog
        npm install @radix-ui/react-avatar
        npm install @radix-ui/react-checkbox
        npm install @radix-ui/react-collapsible
        npm install @radix-ui/react-dialog
        npm install @radix-ui/react-dropdown-menu
        npm install @radix-ui/react-hover-card
        npm install @radix-ui/react-label
        npm install @radix-ui/react-menubar
        npm install @radix-ui/react-navigation-menu
        npm install @radix-ui/react-popover
        npm install @radix-ui/react-progress
        npm install @radix-ui/react-radio-group
        npm install @radix-ui/react-scroll-area
        npm install @radix-ui/react-select
        npm install @radix-ui/react-separator
        npm install @radix-ui/react-slider
        npm install @radix-ui/react-switch
        npm install @radix-ui/react-tabs
        npm install @radix-ui/react-toggle
        npm install @radix-ui/react-toggle-group
        npm install @radix-ui/react-tooltip

    - name: Create package.json
      run: |
        cat > package.json << 'EOF'
        {
          "name": "comment-interested",
          "version": "1.0.0",
          "type": "module",
          "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview"
          },
          "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0"
          },
          "devDependencies": {
            "@types/react": "^18.2.0",
            "@types/react-dom": "^18.2.0",
            "@vitejs/plugin-react": "^4.0.0",
            "typescript": "^5.0.0",
            "vite": "^4.0.0"
          }
        }
        EOF

    - name: Create vite.config.js
      run: |
        cat > vite.config.js << 'EOF'
        import { defineConfig } from 'vite'
        import react from '@vitejs/plugin-react'

        export default defineConfig({
          plugins: [react()],
          base: process.env.GITHUB_ACTIONS ? '/${{ github.event.repository.name }}/' : '/',
          build: {
            outDir: 'dist',
            assetsDir: 'assets',
            sourcemap: false
          }
        })
        EOF

    - name: Create index.html
      run: |
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Comment Interested - LinkedIn Search Mastery</title>
          </head>
          <body>
            <div id="root"></div>
            <script type="module" src="/src/main.tsx"></script>
          </body>
        </html>
        EOF

    - name: Create src/main.tsx
      run: |
        mkdir -p src
        cat > src/main.tsx << 'EOF'
        import React from 'react'
        import ReactDOM from 'react-dom/client'
        import App from './App'
        import './index.css'

        ReactDOM.createRoot(document.getElementById('root')!).render(
          <React.StrictMode>
            <App />
          </React.StrictMode>,
        )
        EOF

    - name: Move App.tsx to src
      run: |
        mv App.tsx src/
        mv components src/
        mv styles src/

    - name: Create src/index.css
      run: |
        cat > src/index.css << 'EOF'
        @import 'styles/globals.css';
        EOF

    - name: Update imports in components
      run: |
        find src/components -name "*.tsx" -exec sed -i 's|"./components/|"../components/|g' {} \;
        find src/components -name "*.tsx" -exec sed -i 's|from "./|from "../|g' {} \;

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist